services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade-nfi
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - ./user_data:/freqtrade/user_data
      - ./config:/freqtrade/config
      - ./logs:/freqtrade/logs
    ports:
      - "8081:8080"
    command: >
      trade
      --config /freqtrade/config/config.json
      --strategy NostalgiaForInfinityX6
